# -- Only apps listed here will be rendered.
enabled:
  - bitwarden
  - longhorn
  - smb-driver
  - keda

  - adguard-home
  - adguard-sync

  - home-assistant
  - teamspeak
  - nodered
  - mosquitto
  - n8n

  - jellyfin
