# -- Only apps listed here will be rendered.
enabled:
  - bitwarden
  - local-path-provisioner
  - longhorn
  - smb-driver
  - keda

  - adguard-home
  - cert-manager
  - minio

  - cloudnative-pg

  # testing only
  - hello-world
  - hello-world-simple
