# -- Path to the root of this helm chart within the git repository.
baseDir: 03_apps
# -- The main git repository where the apps are stored. (This repository.)
mainRepo: https://github.com/lunarys/gitops.git
privateRepo: https://github.com/lunarys/gitops-private.git
privateRepoEnabled: true
# -- The helm repository where my base helm charts are stored.
mainHelmRepo: registry.gitlab.com/juulun/helm-charts/charts
# -- The helm repository where the application-wrapper helm chart is stored.
wrapperHelmRepo: oci://ghcr.io/lunarys

# -- The revision of the `mainRepo` to use.
targetRevision: main

# - The helm chart within the `mainHelmRepo` that is used to render secrets.
secretsChart: "externalsecrets"
# - The version of the `secretsChart` to use by default.
secretsChartVersion: "2.10.1"

# -- The helm chart within the `mainHelmRepo` that is used to render network policies
networkPolicyChart: "networkpolicy"
# -- The version of the `networkPolicyChart` to use by default.
networkPolicyChartVersion: "2.10.1"

# -- The values file to use for the application in the respective cluster, e.g. `values-test.yaml`.
# In addition to the default `values.yaml` file.
targetValuesFile: ""
# -- The secrets file to use for the application in the respective cluster, e.g. `secrets-test.yaml`.
# In addition to the default `secrets.yaml` file.
targetSecretsFile: ""
# -- The directory to use for additional resources in the respective cluster, e.g. `resources-test`.
# Currently only applies to `cilium`.
targetResourcesDir: ""

# -- The namespace the ArgoCD applications and projects are created in. Must match the namespace of the ArgoCD instance.
namespace: argocd
# Destination kubernetes cluster.
server: https://kubernetes.default.svc

# -- Only apps listed here will be rendered. Set via `values-[env]-apps.yaml`.
enabled: []

# -- Settings that are passed to the application-wrapper chart as default settings for all apps and projects.
defaultSettings:
  # -- Whether to enable automatic sync by default.
  autoSync: false
  selfHeal: true
  prune: false
  # -- Additional namespaces that should be allowed in a project.
  additionalNamespaces: []
  # -- Whether there are settings in the separate, private gitops repository.
  privateSettings: false
  # -- Whether to use server-side apply by default.
  serverSideApply: true
  skipCrds: true
