# -- Only apps listed here will be rendered.
enabled:
  - bitwarden
  - local-path-provisioner
  - longhorn
  - smb-driver
  - keda

  - adguard-home
  - minio

  # testing only
  - hello-world
  - hello-world-simple
