# Step-CA Certificates ConfigMap
# Fill in the certificates after running: step ca init
apiVersion: v1
kind: ConfigMap
metadata:
  name: step-certificates-certs
data:
  root_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBwzCCAWqgAwIBAgIRAPMhhij8zCTPY+kO+nRljQYwCgYIKoZIzj0EAwIwQDEa
    MBgGA1UEChMRU21hbGxzdGVwIChMb2NhbCkxIjAgBgNVBAMTGVNtYWxsc3RlcCAo
    TG9jYWwpIFJvb3QgQ0EwHhcNMjYwMTI4MTQwNzA1WhcNMzYwMTI2MTQwNzA1WjBA
    MRowGAYDVQQKExFTbWFsbHN0ZXAgKExvY2FsKTEiMCAGA1UEAxMZU21hbGxzdGVw
    IChMb2NhbCkgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABMdHx72L
    btAIqgPySr4qjeFDPGsQDpBsdi+eJmbIuMhoMxsXEcBrITYFTox5yFduUPLckAk7
    HejeOlFbl/tM5g6jRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/
    AgEBMB0GA1UdDgQWBBSzbKgFg9LnLzk+A9VRUwTyB63pATAKBggqhkjOPQQDAgNH
    ADBEAiAK4g9BvKIzrotAg/Ht+0NwBb9SFFVcwBV8jOxj80wzvwIgHK6PGKR5/seM
    oDQZrLO/NoWEsHAdPp7hMctHbyy77wg=
    -----END CERTIFICATE-----
  intermediate_ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB7jCCAZOgAwIBAgIRALf1sjhDRMn4nRD2BFrpLXEwCgYIKoZIzj0EAwIwQDEa
    MBgGA1UEChMRU21hbGxzdGVwIChMb2NhbCkxIjAgBgNVBAMTGVNtYWxsc3RlcCAo
    TG9jYWwpIFJvb3QgQ0EwHhcNMjYwMTI4MTQwNzA2WhcNMzYwMTI2MTQwNzA2WjBI
    MRowGAYDVQQKExFTbWFsbHN0ZXAgKExvY2FsKTEqMCgGA1UEAxMhU21hbGxzdGVw
    IChMb2NhbCkgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
    QgAE0VHZOFo/XKq9S3PfoUTkaKOsH1aSwobBl6ZuR0jZmxuB2mRyIy5LTZTlaQsJ
    aYEOOHaRxyjdN9BfGOKa3xAz86NmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
    /wQIMAYBAf8CAQAwHQYDVR0OBBYEFK86uZm6MPoNoFtIvJhlldw3DcUzMB8GA1Ud
    IwQYMBaAFLNsqAWD0ucvOT4D1VFTBPIHrekBMAoGCCqGSM49BAMCA0kAMEYCIQDW
    0F/nmHiQugADP+FUPvbowifm80rlV115X8WzvOsIegIhAIxHKDgFcE3i+3rgRkQp
    WQIxfzBLGez0Wr5lOloSroFF
    -----END CERTIFICATE-----
