externalsecrets:
  secrets:
    s3-credentials:
      commonRemoteKey: "7778bd62-ca44-4cbb-a56c-b3a400b28ac1"
    db-superuser:
      commonRemoteKey: "2711c72a-ae8f-4ff1-aa92-b3c500cb7f46"

s3:
  backupBucket: "cloudnative-pg-backup-prod"
