# https://github.com/cloudnative-pg/charts/tree/main/charts/cloudnative-pg
config:
  clusterWide: false  # can be disabled if only running a single database in the namespace

  data:
    INHERITED_LABELS: "custom.network/*"
