apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traefik-project
spec:
  description: Traefik Project
  sourceRepos:
    - {{ .Values.mainRepo }}
    - {{ .Values.mainHelmRepo | trimPrefix "oci://" }}
  destinations:
    - namespace: traefik
      server: {{ .Values.server }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources:
    warn: false
