ingress:
  enabled: false

image:
  name: docker.io/teamspeak
  tag: 3.13.7

service:
  port: 9987
  targetPort: 9987
  protocol: UDP
  externalIPs:
    - 10.0.4.10

networkpolicy:
  enabled: true
  preset:
    ingress:
      fromWorld: true

longhornstorage:
  volumes:
    ts3-server-data:
      size: 50Mi
      variant: retain
      pvName: "pvc-35928dca-0da6-4366-a46e-f8b491b448d0"
      mount:
        path: "/var/ts3server"

env:
  TS3SERVER_LICENSE: "accept"

podSecurityContextPreset:
  # user used in the official container image. required for correct file access. 
  runAsUser: 9987

livenessProbe:
  enabled: true
  tcp:
    port: 10011 # TeamSpeak provides a TCP admin interface on port 10011 by default

readinessProbe:
  enabled: true
  tcp:
    port: 10011 # TeamSpeak provides a TCP admin interface on port 10011 by default
